# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field

from .._internal import NameIdPair


class BackupInfo(BaseModel):
    server_version: str | None = Field(None, alias="ServerVersion")
    plugin_version: str | None = Field(None, alias="PluginVersion")
    name: str | None = Field(None, alias="Name")
    can_restore: bool | None = Field(None, alias="CanRestore")
    is_full_backup: bool | None = Field(None, alias="IsFullBackup")
    date_created: AwareDatetime | None = Field(None, alias="DateCreated")
    users: list[NameIdPair] | None = Field(None, alias="Users")
