# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import BackupInfo


class RestoreOptions(BaseModel):
    restore_server_id: bool | None = Field(None, alias="RestoreServerId")
    use_files: str | None = Field(None, alias="UseFiles")


class UserRestoreInfo(BaseModel):
    source_user_id: str | None = Field(None, alias="SourceUserId")
    target_user_id: str | None = Field(None, alias="TargetUserId")


class DataRestoreOptions(BaseModel):
    users: list[UserRestoreInfo] | None = Field(None, alias="Users")


class AllBackupsInfo(BaseModel):
    full_backup_info: BackupInfo | None = Field(None, alias="FullBackupInfo")
    light_backups: list[BackupInfo] | None = Field(None, alias="LightBackups")
