# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ThumbnailInfo(BaseModel):
    position_ticks: int | None = Field(None, alias="PositionTicks")
    image_tag: str | None = Field(None, alias="ImageTag")


class ThumbnailSetInfo(BaseModel):
    aspect_ratio: float | None = Field(None, alias="AspectRatio")
    thumbnails: list[ThumbnailInfo] | None = Field(None, alias="Thumbnails")
