# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class EditorTypes(
    RootModel[
        Literal[
            "Group",
            "Text",
            "Numeric",
            "Boolean",
            "SelectSingle",
            "SelectMultiple",
            "Date",
            "FilePath",
            "FolderPath",
            "StatusItem",
            "ProgressItem",
            "ButtonItem",
            "ButtonGroup",
            "CaptionItem",
            "LabelItem",
            "ItemList",
            "RadioGroup",
            "DxDataGrid",
            "DxPivotGrid",
            "SpacerItem",
        ]
    ]
):
    root: Literal[
        "Group",
        "Text",
        "Numeric",
        "Boolean",
        "SelectSingle",
        "SelectMultiple",
        "Date",
        "FilePath",
        "FolderPath",
        "StatusItem",
        "ProgressItem",
        "ButtonItem",
        "ButtonGroup",
        "CaptionItem",
        "LabelItem",
        "ItemList",
        "RadioGroup",
        "DxDataGrid",
        "DxPivotGrid",
        "SpacerItem",
    ]
