# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from .._internal import ICodecDeviceCapabilities, ICodecDeviceInfo

__all__ = ["ICodecDeviceCapabilities", "ICodecDeviceInfo"]
