# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from .._internal import Version


class IPlugin(BaseModel):
    name: str | None = Field(None, alias="Name")
    description: str | None = Field(None, alias="Description")
    id: str | None = Field(None, alias="Id")
    version: Version | None = Field(None, alias="Version")
    assembly_file_path: str | None = Field(None, alias="AssemblyFilePath")
    data_folder_path: str | None = Field(None, alias="DataFolderPath")
