# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class AddressFamily(
    RootModel[
        Literal[
            "Unspecified",
            "Unix",
            "InterNetwork",
            "ImpLink",
            "Pup",
            "Chaos",
            "NS",
            "Ipx",
            "Iso",
            "Osi",
            "Ecma",
            "DataKit",
            "Ccitt",
            "Sna",
            "DecNet",
            "DataLink",
            "Lat",
            "HyperChannel",
            "AppleTalk",
            "NetBios",
            "VoiceView",
            "FireFox",
            "Banyan",
            "Atm",
            "InterNetworkV6",
            "Cluster",
            "Ieee12844",
            "Irda",
            "NetworkDesigners",
            "Max",
            "Packet",
            "ControllerAreaNetwork",
            "Unknown",
        ]
    ]
):
    root: Literal[
        "Unspecified",
        "Unix",
        "InterNetwork",
        "ImpLink",
        "Pup",
        "Chaos",
        "NS",
        "Ipx",
        "Iso",
        "Osi",
        "Ecma",
        "DataKit",
        "Ccitt",
        "Sna",
        "DecNet",
        "DataLink",
        "Lat",
        "HyperChannel",
        "AppleTalk",
        "NetBios",
        "VoiceView",
        "FireFox",
        "Banyan",
        "Atm",
        "InterNetworkV6",
        "Cluster",
        "Ieee12844",
        "Irda",
        "NetworkDesigners",
        "Max",
        "Packet",
        "ControllerAreaNetwork",
        "Unknown",
    ]
