# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, RootModel

from .._internal import (
    CodecProfile,
    ContainerProfile,
    DirectPlayProfile,
    ResponseProfile,
    SubtitleProfile,
    TranscodingProfile,
)


class DeviceProfileType(RootModel[Literal["System", "User"]]):
    root: Literal["System", "User"]


class HeaderMatchType(RootModel[Literal["Equals", "Regex", "Substring"]]):
    root: Literal["Equals", "Regex", "Substring"]


class ProtocolInfoDetection(BaseModel):
    enabled_for_video: bool | None = Field(None, alias="EnabledForVideo")
    enabled_for_audio: bool | None = Field(None, alias="EnabledForAudio")
    enabled_for_photos: bool | None = Field(None, alias="EnabledForPhotos")


class HttpHeaderInfo(BaseModel):
    name: str | None = Field(None, alias="Name")
    value: str | None = Field(None, alias="Value")
    match: HeaderMatchType | None = Field(None, alias="Match")


class DeviceIdentification(BaseModel):
    friendly_name: str | None = Field(None, alias="FriendlyName")
    model_number: str | None = Field(None, alias="ModelNumber")
    serial_number: str | None = Field(None, alias="SerialNumber")
    model_name: str | None = Field(None, alias="ModelName")
    model_description: str | None = Field(None, alias="ModelDescription")
    device_description: str | None = Field(None, alias="DeviceDescription")
    model_url: str | None = Field(None, alias="ModelUrl")
    manufacturer: str | None = Field(None, alias="Manufacturer")
    manufacturer_url: str | None = Field(None, alias="ManufacturerUrl")
    headers: list[HttpHeaderInfo] | None = Field(None, alias="Headers")


class DlnaProfile(BaseModel):
    type: DeviceProfileType | None = Field(None, alias="Type")
    path: str | None = Field(None, alias="Path")
    user_id: str | None = Field(None, alias="UserId")
    album_art_pn: str | None = Field(None, alias="AlbumArtPn")
    max_album_art_width: int | None = Field(None, alias="MaxAlbumArtWidth")
    max_album_art_height: int | None = Field(None, alias="MaxAlbumArtHeight")
    max_icon_width: int | None = Field(None, alias="MaxIconWidth")
    max_icon_height: int | None = Field(None, alias="MaxIconHeight")
    friendly_name: str | None = Field(None, alias="FriendlyName")
    manufacturer: str | None = Field(None, alias="Manufacturer")
    manufacturer_url: str | None = Field(None, alias="ManufacturerUrl")
    model_name: str | None = Field(None, alias="ModelName")
    model_description: str | None = Field(None, alias="ModelDescription")
    model_number: str | None = Field(None, alias="ModelNumber")
    model_url: str | None = Field(None, alias="ModelUrl")
    serial_number: str | None = Field(None, alias="SerialNumber")
    enable_album_art_in_didl: bool | None = Field(None, alias="EnableAlbumArtInDidl")
    enable_single_album_art_limit: bool | None = Field(
        None, alias="EnableSingleAlbumArtLimit"
    )
    enable_single_subtitle_limit: bool | None = Field(
        None, alias="EnableSingleSubtitleLimit"
    )
    protocol_info: str | None = Field(None, alias="ProtocolInfo")
    timeline_offset_seconds: int | None = Field(None, alias="TimelineOffsetSeconds")
    requires_plain_video_items: bool | None = Field(
        None, alias="RequiresPlainVideoItems"
    )
    requires_plain_folders: bool | None = Field(None, alias="RequiresPlainFolders")
    ignore_transcode_byte_range_requests: bool | None = Field(
        None, alias="IgnoreTranscodeByteRangeRequests"
    )
    supports_samsung_bookmark: bool | None = Field(
        None, alias="SupportsSamsungBookmark"
    )
    identification: DeviceIdentification | None = Field(None, alias="Identification")
    protocol_info_detection: ProtocolInfoDetection | None = Field(
        None, alias="ProtocolInfoDetection"
    )
    name: str | None = Field(None, alias="Name")
    id: str | None = Field(None, alias="Id")
    supported_media_types: str | None = Field(None, alias="SupportedMediaTypes")
    max_streaming_bitrate: int | None = Field(None, alias="MaxStreamingBitrate")
    music_streaming_transcoding_bitrate: int | None = Field(
        None, alias="MusicStreamingTranscodingBitrate"
    )
    max_static_music_bitrate: int | None = Field(None, alias="MaxStaticMusicBitrate")
    declared_features: list[str] | None = Field(None, alias="DeclaredFeatures")
    direct_play_profiles: list[DirectPlayProfile] | None = Field(
        None, alias="DirectPlayProfiles"
    )
    transcoding_profiles: list[TranscodingProfile] | None = Field(
        None, alias="TranscodingProfiles"
    )
    container_profiles: list[ContainerProfile] | None = Field(
        None, alias="ContainerProfiles"
    )
    codec_profiles: list[CodecProfile] | None = Field(None, alias="CodecProfiles")
    response_profiles: list[ResponseProfile] | None = Field(
        None, alias="ResponseProfiles"
    )
    subtitle_profiles: list[SubtitleProfile] | None = Field(
        None, alias="SubtitleProfiles"
    )
