# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from datetime import time as time_aliased

from pydantic import BaseModel, Field


class ProcessMetricPoint(BaseModel):
    time: time_aliased | None = Field(None, alias="Time")
    cpu_percent: float | None = Field(None, alias="CpuPercent")
    virtual_memory: float | None = Field(None, alias="VirtualMemory")
    working_set: float | None = Field(None, alias="WorkingSet")


class ProcessStatistics(BaseModel):
    current_cpu: float | None = Field(None, alias="CurrentCpu")
    average_cpu: float | None = Field(None, alias="AverageCpu")
    current_virtual_memory: float | None = Field(None, alias="CurrentVirtualMemory")
    current_working_set: float | None = Field(None, alias="CurrentWorkingSet")
    metrics: list[ProcessMetricPoint] | None = Field(None, alias="Metrics")
