# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class PostbackAction(BaseModel):
    target_editor_id: str | None = Field(None, alias="TargetEditorId")
    postback_command_id: str | None = Field(None, alias="PostbackCommandId")
    command_parameter_property_id: str | None = Field(
        None, alias="CommandParameterPropertyId"
    )
