# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field

from . import Plugins
from ._internal import (
    BaseItemDto,
    DayOfWeek,
    ItemLinkType,
    KeywordType,
    PersonType,
    ProgressEvent,
    SleepTimerMode,
)
from .Common import Plugins as Plugins_1


class SetChannelMapping(BaseModel):
    tuner_channel_id: str | None = Field(None, alias="TunerChannelId")
    provider_channel_id: str | None = Field(None, alias="ProviderChannelId")


class NameIdDescriptionPair(BaseModel):
    short_overview: str | None = Field(None, alias="ShortOverview")
    name: str | None = Field(None, alias="Name")
    id: str | None = Field(None, alias="Id")


class AddAdminNotification(BaseModel):
    display_date_time: bool | None = Field(None, alias="DisplayDateTime")


class TagItem(BaseModel):
    name: str | None = Field(None, alias="Name")
    id: str | None = Field(None, alias="Id")


class ListingProviderTypeInfo(BaseModel):
    name: str | None = Field(None, alias="Name")
    id: str | None = Field(None, alias="Id")
    setup_url: str | None = Field(None, alias="SetupUrl")


class SetChannelDisabled(BaseModel):
    id: str | None = Field(None, alias="Id")
    management_id: str | None = Field(None, alias="ManagementId")
    disabled: bool | None = Field(None, alias="Disabled")


class SetChannelSortIndex(BaseModel):
    id: str | None = Field(None, alias="Id")
    management_id: str | None = Field(None, alias="ManagementId")
    new_index: int | None = Field(None, alias="NewIndex")


class OnPlaybackProgress(BaseModel):
    playlist_index: int | None = Field(None, alias="PlaylistIndex")
    playlist_length: int | None = Field(None, alias="PlaylistLength")
    shuffle: bool | None = Field(None, alias="Shuffle")
    sleep_timer_mode: SleepTimerMode | None = Field(None, alias="SleepTimerMode")
    sleep_timer_end_time: AwareDatetime | None = Field(None, alias="SleepTimerEndTime")
    event_name: ProgressEvent | None = Field(None, alias="EventName")


class BaseItemsRequest(BaseModel):
    is_special_episode: bool | None = Field(None, alias="IsSpecialEpisode")
    is4_k: bool | None = Field(None, alias="Is4K")
    min_date_created: AwareDatetime | None = Field(None, alias="MinDateCreated")
    max_date_created: AwareDatetime | None = Field(None, alias="MaxDateCreated")
    enable_total_record_count: bool | None = Field(None, alias="EnableTotalRecordCount")
    match_any_word: bool | None = Field(None, alias="MatchAnyWord")
    is_duplicate: bool | None = Field(None, alias="IsDuplicate")
    name: str | None = Field(None, alias="Name")
    recording_keyword: str | None = Field(None, alias="RecordingKeyword")
    recording_keyword_type: KeywordType | None = Field(
        None, alias="RecordingKeywordType"
    )
    random_seed: int | None = Field(None, alias="RandomSeed")
    genre_ids: str | None = Field(None, alias="GenreIds")
    collection_ids: str | None = Field(None, alias="CollectionIds")
    tag_ids: str | None = Field(None, alias="TagIds")
    exclude_tag_ids: str | None = Field(None, alias="ExcludeTagIds")
    item_person_types: list[PersonType] | None = Field(None, alias="ItemPersonTypes")
    exclude_artist_ids: str | None = Field(None, alias="ExcludeArtistIds")
    album_artist_ids: str | None = Field(None, alias="AlbumArtistIds")
    composer_artist_ids: str | None = Field(None, alias="ComposerArtistIds")
    contributing_artist_ids: str | None = Field(None, alias="ContributingArtistIds")
    album_ids: str | None = Field(None, alias="AlbumIds")
    outer_ids: str | None = Field(None, alias="OuterIds")
    list_item_ids: str | None = Field(None, alias="ListItemIds")
    audio_languages: str | None = Field(None, alias="AudioLanguages")
    subtitle_languages: str | None = Field(None, alias="SubtitleLanguages")
    can_edit_items: bool | None = Field(None, alias="CanEditItems")
    group_items_into: ItemLinkType | None = Field(None, alias="GroupItemsInto")
    is_standalone_special: bool | None = Field(None, alias="IsStandaloneSpecial")
    min_width: int | None = Field(None, alias="MinWidth")
    min_height: int | None = Field(None, alias="MinHeight")
    max_width: int | None = Field(None, alias="MaxWidth")
    max_height: int | None = Field(None, alias="MaxHeight")
    group_programs_by_series: bool | None = Field(None, alias="GroupProgramsBySeries")
    group_by_presentation_unique_key: bool | None = Field(
        None, alias="GroupByPresentationUniqueKey"
    )
    air_days: list[DayOfWeek] | None = Field(None, alias="AirDays")
    is_airing: bool | None = Field(None, alias="IsAiring")
    has_aired: bool | None = Field(None, alias="HasAired")
    collection_types: str | None = Field(None, alias="CollectionTypes")
    exclude_sources: list[str] | None = Field(None, alias="ExcludeSources")


class AvailableRecordingOptions(BaseModel):
    recording_folders: list[NameIdDescriptionPair] | None = Field(
        None, alias="RecordingFolders"
    )
    movie_recording_folders: list[NameIdDescriptionPair] | None = Field(
        None, alias="MovieRecordingFolders"
    )
    series_recording_folders: list[NameIdDescriptionPair] | None = Field(
        None, alias="SeriesRecordingFolders"
    )


class ConfigurationPageInfo(BaseModel):
    name: str | None = Field(None, alias="Name")
    enable_in_main_menu: bool | None = Field(None, alias="EnableInMainMenu")
    enable_in_user_menu: bool | None = Field(None, alias="EnableInUserMenu")
    feature_id: str | None = Field(None, alias="FeatureId")
    menu_section: str | None = Field(None, alias="MenuSection")
    menu_icon: str | None = Field(None, alias="MenuIcon")
    display_name: str | None = Field(None, alias="DisplayName")
    configuration_page_type: Plugins.ConfigurationPageType | None = Field(
        None, alias="ConfigurationPageType"
    )
    plugin_id: str | None = Field(None, alias="PluginId")
    href: str | None = Field(None, alias="Href")
    nav_menu_id: str | None = Field(None, alias="NavMenuId")
    plugin: Plugins_1.IPlugin | None = Field(None, alias="Plugin")
    translations: list[str] | None = Field(None, alias="Translations")


class EpgRow(BaseModel):
    channel: BaseItemDto | None = Field(None, alias="Channel")
    programs: list[BaseItemDto] | None = Field(None, alias="Programs")
