# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class SimpleCondition(
    RootModel[Literal["IsTrue", "IsFalse", "IsNull", "IsNotNullOrEmpty"]]
):
    root: Literal["IsTrue", "IsFalse", "IsNull", "IsNotNullOrEmpty"]


class ValueCondition(
    RootModel[
        Literal[
            "IsEqual",
            "IsNotEqual",
            "IsGreater",
            "IsGreaterOrEqual",
            "IsLess",
            "IsLessOrEqual",
        ]
    ]
):
    root: Literal[
        "IsEqual",
        "IsNotEqual",
        "IsGreater",
        "IsGreaterOrEqual",
        "IsLess",
        "IsLessOrEqual",
    ]
