# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import Session
from ._internal import UserDto


class AuthenticationResult(BaseModel):
    user: UserDto | None = Field(None, alias="User")
    session_info: Session.SessionInfo | None = Field(None, alias="SessionInfo")
    access_token: str | None = Field(None, alias="AccessToken")
    server_id: str | None = Field(None, alias="ServerId")
