# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class BrandingOptions(BaseModel):
    login_disclaimer: str | None = Field(None, alias="LoginDisclaimer")
    custom_css: str | None = Field(None, alias="CustomCss")
