# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class CollectionCreationResult(BaseModel):
    id: str | None = Field(None, alias="Id")
    name: str | None = Field(None, alias="Name")
