# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel

from . import Attributes


class PropertyConditionType(RootModel[Literal["Visible", "Enabled"]]):
    root: Literal["Visible", "Enabled"]


class PropertyCondition(BaseModel):
    affected_property_id: str | None = Field(None, alias="AffectedPropertyId")
    condition_type: PropertyConditionType | None = Field(None, alias="ConditionType")
    target_property_id: str | None = Field(None, alias="TargetPropertyId")
    simple_condition: Attributes.SimpleCondition | None = Field(
        None, alias="SimpleCondition"
    )
    value_condition: Attributes.ValueCondition | None = Field(
        None, alias="ValueCondition"
    )
    value: dict[str, Any] | None = Field(None, alias="Value")
