# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, RootModel


class UserLinkType(RootModel[Literal["LinkedUser", "Guest"]]):
    root: Literal["LinkedUser", "Guest"]


class ConnectAuthenticationExchangeResult(BaseModel):
    local_user_id: str | None = Field(None, alias="LocalUserId")
    access_token: str | None = Field(None, alias="AccessToken")


class UserLinkResult(BaseModel):
    is_pending: bool | None = Field(None, alias="IsPending")
    is_new_user_invitation: bool | None = Field(None, alias="IsNewUserInvitation")
    guest_display_name: str | None = Field(None, alias="GuestDisplayName")
