# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from ipaddress import IPv4Address

from pydantic import AwareDatetime, BaseModel, Field


class DeviceInfo(BaseModel):
    name: str | None = Field(None, alias="Name")
    id: str | None = Field(None, alias="Id")
    internal_id: int | None = Field(None, alias="InternalId")
    reported_device_id: str | None = Field(None, alias="ReportedDeviceId")
    last_user_name: str | None = Field(None, alias="LastUserName")
    app_name: str | None = Field(None, alias="AppName")
    app_version: str | None = Field(None, alias="AppVersion")
    last_user_id: str | None = Field(None, alias="LastUserId")
    date_last_activity: AwareDatetime | None = Field(None, alias="DateLastActivity")
    icon_url: str | None = Field(None, alias="IconUrl")
    ip_address: IPv4Address | None = Field(None, alias="IpAddress")


class DeviceOptions(BaseModel):
    custom_name: str | None = Field(None, alias="CustomName")


class LocalFileInfo(BaseModel):
    name: str | None = Field(None, alias="Name")
    id: str | None = Field(None, alias="Id")
    album: str | None = Field(None, alias="Album")
    mime_type: str | None = Field(None, alias="MimeType")
    date_created: AwareDatetime | None = Field(None, alias="DateCreated")


class ContentUploadHistory(BaseModel):
    device_id: str | None = Field(None, alias="DeviceId")
    files_uploaded: list[LocalFileInfo] | None = Field(None, alias="FilesUploaded")
