# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import Actions, Common, Conditions


class EditorBase(BaseModel):
    editor_type: Common.EditorTypes | None = Field(None, alias="EditorType")
    name: str | None = Field(None, alias="Name")
    id: str | None = Field(None, alias="Id")
    allow_empty: bool | None = Field(None, alias="AllowEmpty")
    is_read_only: bool | None = Field(None, alias="IsReadOnly")
    is_advanced: bool | None = Field(None, alias="IsAdvanced")
    display_name: str | None = Field(None, alias="DisplayName")
    description: str | None = Field(None, alias="Description")
    feature_requires_premiere: bool | None = Field(
        None, alias="FeatureRequiresPremiere"
    )
    parent_id: str | None = Field(None, alias="ParentId")


class EditorButtonItem(BaseModel):
    editor_type: Common.EditorTypes | None = Field(None, alias="EditorType")
    name: str | None = Field(None, alias="Name")
    id: str | None = Field(None, alias="Id")
    allow_empty: bool | None = Field(None, alias="AllowEmpty")
    is_read_only: bool | None = Field(None, alias="IsReadOnly")
    is_advanced: bool | None = Field(None, alias="IsAdvanced")
    display_name: str | None = Field(None, alias="DisplayName")
    description: str | None = Field(None, alias="Description")
    feature_requires_premiere: bool | None = Field(
        None, alias="FeatureRequiresPremiere"
    )
    parent_id: str | None = Field(None, alias="ParentId")


class EditorRoot(BaseModel):
    property_conditions: list[Conditions.PropertyCondition] | None = Field(
        None, alias="PropertyConditions"
    )
    postback_actions: list[Actions.PostbackAction] | None = Field(
        None, alias="PostbackActions"
    )
    title_button: EditorButtonItem | None = Field(None, alias="TitleButton")
    editor_items: list[EditorBase] | None = Field(None, alias="EditorItems")
    editor_type: Common.EditorTypes | None = Field(None, alias="EditorType")
    name: str | None = Field(None, alias="Name")
    id: str | None = Field(None, alias="Id")
    allow_empty: bool | None = Field(None, alias="AllowEmpty")
    is_read_only: bool | None = Field(None, alias="IsReadOnly")
    is_advanced: bool | None = Field(None, alias="IsAdvanced")
    display_name: str | None = Field(None, alias="DisplayName")
    description: str | None = Field(None, alias="Description")
    feature_requires_premiere: bool | None = Field(
        None, alias="FeatureRequiresPremiere"
    )
    parent_id: str | None = Field(None, alias="ParentId")
