# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field

from . import Connect, Drawing
from ._internal import ImageType, LinkedItemInfo


class ItemImageInfo(BaseModel):
    path: str | None = Field(None, alias="Path")
    type: ImageType | None = Field(None, alias="Type")
    orientation: Drawing.ImageOrientation | None = Field(None, alias="Orientation")
    date_modified: AwareDatetime | None = Field(None, alias="DateModified")
    width: int | None = Field(None, alias="Width")
    height: int | None = Field(None, alias="Height")


class User(BaseModel):
    uses_id_for_configuration_path: bool | None = Field(
        None, alias="UsesIdForConfigurationPath"
    )
    password: str | None = Field(None, alias="Password")
    easy_password: str | None = Field(None, alias="EasyPassword")
    salt: str | None = Field(None, alias="Salt")
    connect_user_name: str | None = Field(None, alias="ConnectUserName")
    connect_user_id: str | None = Field(None, alias="ConnectUserId")
    connect_link_type: Connect.UserLinkType | None = Field(
        None, alias="ConnectLinkType"
    )
    connect_access_key: str | None = Field(None, alias="ConnectAccessKey")
    image_infos: list[ItemImageInfo] | None = Field(None, alias="ImageInfos")
    name: str | None = Field(None, alias="Name")
    last_login_date: AwareDatetime | None = Field(None, alias="LastLoginDate")
    last_activity_date: AwareDatetime | None = Field(None, alias="LastActivityDate")
    played_percentage: float | None = Field(None, alias="PlayedPercentage")
    recursive_child_count_equals_child_count: bool | None = Field(
        None, alias="RecursiveChildCountEqualsChildCount"
    )
    original_parsed_name: str | None = Field(None, alias="OriginalParsedName")
    is_name_parsed_from_folder: bool | None = Field(
        None, alias="IsNameParsedFromFolder"
    )
    id_string: str | None = Field(None, alias="IdString")
    date_created: AwareDatetime | None = Field(None, alias="DateCreated")
    imported_collections: list[LinkedItemInfo] | None = Field(
        None, alias="ImportedCollections"
    )
    resolved_presentation_unique_key: str | None = Field(
        None, alias="ResolvedPresentationUniqueKey"
    )
