# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class UIViewType(RootModel[Literal["RegularPage", "Dialog", "Wizard"]]):
    root: Literal["RegularPage", "Dialog", "Wizard"]


class UICommandType(
    RootModel[
        Literal[
            "Custom",
            "WizardCancel",
            "WizardBack",
            "WizardNext",
            "WizardFinish",
            "DialogCancel",
            "DialogOk",
            "PageSave",
            "PageBack",
            "WizardButton1",
            "WizardButton2",
            "WizardButton3",
        ]
    ]
):
    root: Literal[
        "Custom",
        "WizardCancel",
        "WizardBack",
        "WizardNext",
        "WizardFinish",
        "DialogCancel",
        "DialogOk",
        "PageSave",
        "PageBack",
        "WizardButton1",
        "WizardButton2",
        "WizardButton3",
    ]
