# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class IEditObjectContainer(BaseModel):
    object: dict[str, Any] | None = Field(None, alias="Object")
    default_object: dict[str, Any] | None = Field(None, alias="DefaultObject")
    type_name: str | None = Field(None, alias="TypeName")
