# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class LocalizatonOption(BaseModel):
    name: str | None = Field(None, alias="Name")
    value: str | None = Field(None, alias="Value")


class CountryInfo(BaseModel):
    name: str | None = Field(None, alias="Name")
    display_name: str | None = Field(None, alias="DisplayName")
    english_name: str | None = Field(None, alias="EnglishName")
    two_letter_iso_region_name: str | None = Field(None, alias="TwoLetterISORegionName")
    three_letter_iso_region_name: str | None = Field(
        None, alias="ThreeLetterISORegionName"
    )


class CultureDto(BaseModel):
    name: str | None = Field(None, alias="Name")
    display_name: str | None = Field(None, alias="DisplayName")
    two_letter_iso_language_name: str | None = Field(
        None, alias="TwoLetterISOLanguageName"
    )
    three_letter_iso_language_name: str | None = Field(
        None, alias="ThreeLetterISOLanguageName"
    )
    three_letter_iso_language_names: list[str] | None = Field(
        None, alias="ThreeLetterISOLanguageNames"
    )
    two_letter_iso_language_names: list[str] | None = Field(
        None, alias="TwoLetterISOLanguageNames"
    )
