# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, RootModel


class FileSystemEntryType(
    RootModel[Literal["File", "Directory", "NetworkComputer", "NetworkShare"]]
):
    root: Literal["File", "Directory", "NetworkComputer", "NetworkShare"]


class FileSystemEntryInfo(BaseModel):
    name: str | None = Field(None, alias="Name")
    path: str | None = Field(None, alias="Path")
    type: FileSystemEntryType | None = Field(None, alias="Type")
