# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Literal

from pydantic import RootModel


class NotificationLevel(RootModel[Literal["Normal", "Warning", "Error"]]):
    root: Literal["Normal", "Warning", "Error"]
