# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class IntroDebugInfo(BaseModel):
    id: int | None = Field(None, alias="Id")
    path: str | None = Field(None, alias="Path")
    start: int | None = Field(None, alias="Start")
    end: int | None = Field(None, alias="End")
