# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class PlaylistCreationResult(BaseModel):
    id: str | None = Field(None, alias="Id")
    name: str | None = Field(None, alias="Name")
    item_added_count: int | None = Field(None, alias="ItemAddedCount")


class AddToPlaylistInfo(BaseModel):
    item_count: int | None = Field(None, alias="ItemCount")
    contains_duplicates: bool | None = Field(None, alias="ContainsDuplicates")


class AddToPlaylistResult(BaseModel):
    id: str | None = Field(None, alias="Id")
    item_added_count: int | None = Field(None, alias="ItemAddedCount")
