# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, RootModel


class PluginInfo(BaseModel):
    name: str | None = Field(None, alias="Name")
    version: str | None = Field(None, alias="Version")
    configuration_file_name: str | None = Field(None, alias="ConfigurationFileName")
    description: str | None = Field(None, alias="Description")
    id: str | None = Field(None, alias="Id")
    image_tag: str | None = Field(None, alias="ImageTag")


class ConfigurationPageType(RootModel[Literal["PluginConfiguration", "None"]]):
    root: Literal["PluginConfiguration", "None"]
