# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from ._internal import SeriesTimerInfoDto as SeriesTimerInfoDto_1
from ._internal import TimerInfoDto as TimerInfoDto_1


class SeriesTimerInfoDto(BaseModel):
    items: list[SeriesTimerInfoDto_1] | None = Field(None, alias="Items")
    total_record_count: int | None = Field(None, alias="TotalRecordCount")


class TimerInfoDto(BaseModel):
    items: list[TimerInfoDto_1] | None = Field(None, alias="Items")
    total_record_count: int | None = Field(None, alias="TotalRecordCount")
