# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import Api


class EpgRow(BaseModel):
    items: list[Api.EpgRow] | None = Field(None, alias="Items")
    total_record_count: int | None = Field(None, alias="TotalRecordCount")
