# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from ipaddress import IPv4Address

from pydantic import AwareDatetime, BaseModel, Field

from . import Entities
from ._internal import BaseItemDto, PlayerStateInfo, SessionUserInfo, TranscodingInfo


class SessionInfo(BaseModel):
    play_state: PlayerStateInfo | None = Field(None, alias="PlayState")
    additional_users: list[SessionUserInfo] | None = Field(
        None, alias="AdditionalUsers"
    )
    remote_end_point: IPv4Address | None = Field(None, alias="RemoteEndPoint")
    protocol: str | None = Field(None, alias="Protocol")
    playable_media_types: list[str] | None = Field(None, alias="PlayableMediaTypes")
    playlist_item_id: str | None = Field(None, alias="PlaylistItemId")
    playlist_index: int | None = Field(None, alias="PlaylistIndex")
    playlist_length: int | None = Field(None, alias="PlaylistLength")
    id: str | None = Field(None, alias="Id")
    server_id: str | None = Field(None, alias="ServerId")
    user_id: str | None = Field(None, alias="UserId")
    party_id: str | None = Field(None, alias="PartyId")
    user_name: str | None = Field(None, alias="UserName")
    user_primary_image_tag: str | None = Field(None, alias="UserPrimaryImageTag")
    client: str | None = Field(None, alias="Client")
    last_activity_date: AwareDatetime | None = Field(None, alias="LastActivityDate")
    device_name: str | None = Field(None, alias="DeviceName")
    device_type: str | None = Field(None, alias="DeviceType")
    now_playing_item: BaseItemDto | None = Field(None, alias="NowPlayingItem")
    internal_device_id: int | None = Field(None, alias="InternalDeviceId")
    device_id: str | None = Field(None, alias="DeviceId")
    application_version: str | None = Field(None, alias="ApplicationVersion")
    app_icon_url: str | None = Field(None, alias="AppIconUrl")
    supported_commands: list[str] | None = Field(None, alias="SupportedCommands")
    transcoding_info: TranscodingInfo | None = Field(None, alias="TranscodingInfo")
    supports_remote_control: bool | None = Field(None, alias="SupportsRemoteControl")


class PartyInfo(BaseModel):
    id: str | None = Field(None, alias="Id")
    name: str | None = Field(None, alias="Name")
    sessions: list[SessionInfo] | None = Field(None, alias="Sessions")
    users: list[Entities.User] | None = Field(None, alias="Users")


class PartyInfoResult(BaseModel):
    party_info: PartyInfo | None = Field(None, alias="PartyInfo")
