# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, RootModel


class VpStepTypes(
    RootModel[
        Literal[
            "Decoder",
            "Encoder",
            "Scaling",
            "Deinterlace",
            "SubtitleOverlay",
            "ToneMapping",
            "ColorConversion",
            "SplitCaptions",
            "TextSub2Video",
            "GraphicSub2Video",
            "GraphicSub2Text",
            "BurnInTextSubs",
            "BurnInGraphicSubs",
            "ScaleSubs",
            "TextMod",
            "Censor",
            "ShowSpeaker",
            "StripStyles",
            "ConnectTo",
            "Rotate",
        ]
    ]
):
    root: Literal[
        "Decoder",
        "Encoder",
        "Scaling",
        "Deinterlace",
        "SubtitleOverlay",
        "ToneMapping",
        "ColorConversion",
        "SplitCaptions",
        "TextSub2Video",
        "GraphicSub2Video",
        "GraphicSub2Text",
        "BurnInTextSubs",
        "BurnInGraphicSubs",
        "ScaleSubs",
        "TextMod",
        "Censor",
        "ShowSpeaker",
        "StripStyles",
        "ConnectTo",
        "Rotate",
    ]


class VpStepInfo(BaseModel):
    step_type: VpStepTypes | None = Field(None, alias="StepType")
    step_type_name: str | None = Field(None, alias="StepTypeName")
    hardware_context_name: str | None = Field(None, alias="HardwareContextName")
    is_hardware_context: bool | None = Field(None, alias="IsHardwareContext")
    name: str | None = Field(None, alias="Name")
    short: str | None = Field(None, alias="Short")
    ffmpeg_name: str | None = Field(None, alias="FfmpegName")
    ffmpeg_description: str | None = Field(None, alias="FfmpegDescription")
    ffmpeg_options: str | None = Field(None, alias="FfmpegOptions")
    param: str | None = Field(None, alias="Param")
    param_short: str | None = Field(None, alias="ParamShort")
