# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from ._internal import NameIdPair, UserItemShareLevel


class TagItem(BaseModel):
    name: str | None = Field(None, alias="Name")
    id: str | None = Field(None, alias="Id")


class OfficialRatingItem(BaseModel):
    name: str | None = Field(None, alias="Name")


class LeaveSharedItems(BaseModel):
    item_ids: list[str] | None = Field(None, alias="ItemIds")
    user_id: str | None = Field(None, alias="UserId")


class AddTags(BaseModel):
    tags: list[NameIdPair] | None = Field(None, alias="Tags")


class RemoveTags(BaseModel):
    tags: list[NameIdPair] | None = Field(None, alias="Tags")


class UpdateUserItemAccess(BaseModel):
    item_ids: list[str] | None = Field(None, alias="ItemIds")
    user_ids: list[str] | None = Field(None, alias="UserIds")
    item_access: UserItemShareLevel | None = Field(None, alias="ItemAccess")
