# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-02-21T20:33:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from .._internal import OperatingSystem


class ToneMapOptionsVisibility(BaseModel):
    show_advanced: bool | None = Field(None, alias="ShowAdvanced")
    is_software_tone_mapping_available: bool | None = Field(
        None, alias="IsSoftwareToneMappingAvailable"
    )
    is_any_hardware_tone_mapping_available: bool | None = Field(
        None, alias="IsAnyHardwareToneMappingAvailable"
    )
    show_nvidia_options: bool | None = Field(None, alias="ShowNvidiaOptions")
    show_quick_sync_options: bool | None = Field(None, alias="ShowQuickSyncOptions")
    show_vaapi_options: bool | None = Field(None, alias="ShowVaapiOptions")
    is_open_cl_available: bool | None = Field(None, alias="IsOpenClAvailable")
    is_open_cl_super_t_available: bool | None = Field(
        None, alias="IsOpenClSuperTAvailable"
    )
    is_vaapi_native_available: bool | None = Field(None, alias="IsVaapiNativeAvailable")
    is_quick_sync_native_available: bool | None = Field(
        None, alias="IsQuickSyncNativeAvailable"
    )
    operating_system: OperatingSystem | None = Field(None, alias="OperatingSystem")
